# Generated by Django 3.2.10 on 2022-01-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_contact"),
    ]

    operations = []
